-- plugins/oblsk_anticheat/client/main.lua
--- Movement and health telemetry are now read server-side (AnticheatService
--- polls GetEntityCoords/GetEntityHealth directly, gated on
--- SpawnManagerService's spawn stage) rather than trusted from the client —
--- see docs/superpowers/specs/2026-08-20-anticheat-design.md ("server is
--- the sole source of truth"). Weapon-spawn detection is not wired up yet
--- (no weapon-hash-per-item model exists in this framework — see
--- AnticheatService.lua's comment above where that handler used to be).
--- This file is intentionally empty of any emitServerSecure calls until
--- there's a real client-only signal worth reporting.
